### ISSUE TITLE
Storage scanner

### ISSUE THREAD

**Issue by jaydog175** [McJty/RFToolsControl#100]
Is there a way to directly pull a specified item from a storage scanner? What i'm trying to do is be able to place an item in a inventory (tried to have an item frame but it isn't a recognized inventory) and then have it pull a stack of that item from my storage system using the storage scanner. trying to use enderIO warehouses and storage drawers using an inventory panel from enderIO but the enderIO system isnt very friendly for automation yet and i have no easy way to pull specific items from the warehouses

**Comment by McJty** [comment]
RFTools Control and XNet can do that but otherwise no. The storage scanner is not a real inventory.

**Comment by jaydog175** [comment]
so how would i interact with scanner via xnet?

**Comment by McJty** [comment]
XNet can see the storage scanner as a regular inventory. So you can extract filtered items from it just like you would from a normal chest using XNet
