### ISSUE TITLE
[1.12] Programmer's tooltip are sometime out of the screen

### ISSUE THREAD

**Issue by ExDomino** [McJty/RFToolsControl#102]
When you take your mouse over some buttons of node in the Programmer, the tooltip can be out of the screen. This is very difficult to read if you play with GUI set to auto. Can you fix that please?
http://image.noelshack.com/fichiers/2017/29/6/1500689666-2017-07-21-22-13-28.png

**Comment by josephcsible** [comment]
Fixed in McJtyLib 2.6.2 and above by McJty/McJtyLib@4399d70.
