### ISSUE TITLE
GFX box + GFX line ops render nothing and occasionally result in error

### ISSUE THREAD

**Issue by PolakAllen** [McJty/RFToolsControl#104]
Running a simple setup should hopefully be able to reproduce.

In my setup below, repeat is set to 60 ticks, the sleep before rendering text is 20 ticks (which verifies that rendering does indeed occur). The box and line are never rendered. I wasn't able to determine how often that error occurs, but it's definitely not every cycle, and you should see at least one within a few minutes (playing around with it, it might only occur on Db display)

Occurs in FTB Beyond pack 1.10.2 server
- rftoolsctrl-1.1x-1.6.8.jar
- rftools-1.1x-6.01.jar
- mcjtylib-1.1x-2.3.11.jar

![2017-07-23_21 12 06](https://user-images.githubusercontent.com/4852396/28504863-a971b05e-6feb-11e7-97c2-fe729eea4d27.png)
![setup](https://user-images.githubusercontent.com/4852396/28504834-30b2925a-6feb-11e7-835e-4a4d5564f2fc.png)
![box](https://user-images.githubusercontent.com/4852396/28504919-5a13ef30-6fec-11e7-8792-dae317a73df4.png)
![line](https://user-images.githubusercontent.com/4852396/28504920-5d657852-6fec-11e7-8d1e-c43af0206593.png)
![processor](https://user-images.githubusercontent.com/4852396/28504842-577f3dfc-6feb-11e7-831e-079f18f57e44.png)

**Comment by PolakAllen** [comment]
Further investigation about that internal error shows that it's somehow related to having a second processor. 

I removed it at some point in my troubleshooting, and stop receiving error messages (not positive that I got 0, but the rate was significantly reduced)

Re-adding my second processor resulted in a burst of error messages on immediate placement, followed by errors at the rate that I had been observing

**Comment by PolakAllen** [comment]
I think I found a caching issue that might be causing it:

```
    @Override
    public void gfxClear(IProgram program, @Nullable String id) {
        if (id == null || id.isEmpty()) {
            gfxOps.clear();
            orderedOps.clear();
        } else {
            gfxOps.remove(id);
            orderedOps = null;
        }
        markDirty();
    }

    public Map<String, GfxOp> getGfxOps() {
        return gfxOps;
    }

    public List<String> getOrderedOps() {
        if (orderedOps == null) {
            sortOps();
        }
        return orderedOps;
    }
    private void sortOps() {
        orderedOps = new ArrayList<>(gfxOps.keySet());
        orderedOps.sort(new Comparator<String>() {
            @Override
            public int compare(String s, String t1) {
                return s.compareTo(t1);
            }
        });
    }
```

willing to bet if you change `gfxOps.clear()` to `gfxOps = null`, the issue will go away

hopefully the issue will resolve itself when `readRestorableFromNBT` occurs (I'm not sure when that event is).

**Comment by McJty** [comment]
Thanks for the investigation . I will check it out when I am back from vacation

**Comment by McJty** [comment]
The problem was related but a bit different. I have fixed it for next release
