### ISSUE TITLE
[1.12] Workbench kicks client when trying to craft

### ISSUE THREAD

**Issue by kwpugh** [McJty/RFToolsControl#105]
Forge:  2420

mcjtylib-1.12-2.4.4.jar
rftools-1.12-6.12.jar
rftoolsctrl-1.12-1.6.8.jar
rftoolsdim-1.12-5.04.jar

When you place items on the crafting grid, the client crashes.

Crash report: https://gist.github.com/kwpugh/ed380bfa3348b8f15c4fea9683d12ec2

**Comment by McJty** [comment]
I will check it out when I am back from vacation

**Comment by McJty** [comment]
This is a bug in the 1.12 version only and will be fixed next update
