### ISSUE TITLE
Can't recipe anything

### ISSUE THREAD

**Issue by forestbat** [McJty/RFToolsControl#106]
http://paste.ubuntu.com/25197395/
I wrote a program like DW20，but there are not any materials in the workbench，and the program have no mistake。
![default](https://user-images.githubusercontent.com/23413915/28745279-f70bc9c4-74a7-11e7-9b68-499cd8d206f1.png)
The node adjacent to the workbench is “13”，and the node above the storage scanner is “12”.

**Comment by McJty** [comment]
I am on vacation right now so can't do much but I will check it out when I am back

**Comment by forestbat** [comment]
@McJty Do you finish your vacation？

**Comment by McJty** [comment]
I'll check it out soon

**Comment by forestbat** [comment]
@McJty Yes，5 days has passed。

**Comment by McJty** [comment]
You already showed me your program but that's not enough. I need to know the exact setup of your machines

**Comment by forestbat** [comment]
@McJty 
http://i2.bvimg.com/607376/1791fcaceb67b154.png
As the picture，the node 12 is put above the storage scanner，and the programmer and the crafting station is at the right of the scanner。
http://i2.bvimg.com/607376/c9e2527b9b5d216c.png
The workbench is at the left of the node 13，I want to get materials from the storage scanner to recipe the shield in rftools。
http://i2.bvimg.com/607376/3672aa821c122fd9.png
These are all machines of rftools control。

**Comment by McJty** [comment]
Your program is not correct. If you look at it you can see a flashing light at 3,1. That means there is an error in that opcode. The problem is that you didn't specify all required parameters. You forgot 'SlotOut' (where the output should go in the internal inventory). Let me know if fixing this helps

**Comment by forestbat** [comment]
@McJty 
http://i4.bvimg.com/607376/e7e843e5672006c4.png
I set up the slotout，but there are still not anything reciped，and there are two duplicate events in the crafting station。

**Comment by McJty** [comment]
Can you give me the fixed program?

**Comment by McJty** [comment]
Also a log of the processor. BTW, did you try single stepping it?

**Comment by forestbat** [comment]
http://paste.ubuntu.com/25387595/
I don't know how to single stepping it even if I read the manual。

**Comment by bbgott** [comment]
I believe this is related to #105. There seems to be a major bug with the workbench that is breaking autocrafting

**Comment by McJty** [comment]
I will try to find time to check this out soon

**Comment by McJty** [comment]
This was fixed after #105 was fixed
