### ISSUE TITLE
Multi tank creates liquids from nothing

### ISSUE THREAD

**Issue by secdeath** [McJty/RFToolsControl#107]
I'm attempting to balance lava between a node and two Deep Resonance tanks. The tank on the left has to always be kept at 50% aka 8000mb. I have a program that will either add/subtract the different, or do nothing if it's equal to 8000. Now for some reason, the multi tank connected to my processor seems to create the lava out of thin air. I started out with a drum and 4 DR tanks with hardly any lava. Now they are all full for some reason. I believe there is a bug with the multi tanks causing this.

![2017-08-02_11 34 51](https://user-images.githubusercontent.com/21017396/28886418-adba025a-7776-11e7-9dbe-9649254fb2fa.png)
![2017-08-02_11 34 43](https://user-images.githubusercontent.com/21017396/28886417-adb9eafe-7776-11e7-8ec2-2355e8f5ad92.png)

Let me know what else I can provide to help you folks troubleshoot, please.

**Comment by McJty** [comment]
Versions please?

**Comment by secdeath** [comment]
Sorry i failed you haha.

Minecraft v1.10.2
Deep Resonance - v1.4.8
RF Tools Control v1.6.8

**Comment by secdeath** [comment]
I just tried to do this again and used an empty multi tank from RF Tools Control, and the issue doesn't seem to exist now. I'm still perplexed as to why the multi tank filled almost an entire slot with lava.
