### ISSUE TITLE
[1.12] "Push multiple items" resulting in "internal error"

### ISSUE THREAD

**Issue by Noodlebrain** [McJty/RFToolsControl#108]
Forge version: 2443

I've been attempting to create a recursive autocrafting system with RFTools control [similar to the one here](https://github.com/pagameba/rftc_programs/wiki/Recursive-AutoCrafting), but when I run it, I get "internal error" where "push multiple items" should run, and the crafting ingredients are stuck inside the processor.

Is there a way to resolve this?

**Comment by Noodlebrain** [comment]
Upon further inspection, this might be very slightly related to #105 — when trying the autocraft program, I can push one, and only one, item into the workbench for crafting; attempting to push any more results in the "internal error". I can successfully autocraft 1x1 recipes, but I cannot autocraft anything else.

**Comment by McJty** [comment]
Can I see your program? (do ctrl-c in the programmer and paste it somewhere)
