### ISSUE TITLE
GFX - layering doesn't work as I want to. Maybe bug?

### ISSUE THREAD

**Issue by Ramog** [McJty/RFToolsControl#109]
I wanted to draw a powerbar with a box arround it, It worked verry well but then I tried to make an indicator for something. I used the same technique, first drawing the outside square and then the inside but the inside doesn't show up. I wonder what the problem is. Here are some [pictures](http://imgur.com/a/sNI6c) of my setup.

**Comment by McJty** [comment]
The layers are rendered alphabetically. i.e. the ID you use for the layer is important to determine render order. Are you correctly keeping that in mind?

**Comment by Ramog** [comment]
Oh no I wasn't thanks for pointing that out ^^ Now it owkrs like it should
