### ISSUE TITLE
[1.12.1] Crafting Tweaks Incompatibility.  Breaks Workbench.

### ISSUE THREAD

**Issue by VT-14** [McJty/RFToolsControl#110]
Issue: 
When Crafting Tweaks is installed, the RFTools Control Workbench crashes when items are inserted into it.  Both manual insertion and vanilla Hoppers cause a crash.

Inserting using RFTools Control will return an "Invalid Inventory" error.  Nothing happens (no crash).

Tested in Single Player with only RFTools Control, Crafting Tweaks, JEI, and required mods (McJtyLib and RFTools).

Minecraft: 1.12.1
Forge: 14.22.0.2474
RFTools Control: 1.6.8
Crafting Tweaks: 8.1.5

Manual Insertion Crash Log: https://gist.github.com/VT-14/1f7be2b8e5ea2bca8b723d2e8c95621e

Hopper Insertion Crash Log: https://gist.github.com/VT-14/64669a8a42a40755b5bb3027b5d0849d

Crafting Tweaks Issue: blay09/CraftingTweaks#110

**Comment by McJty** [comment]
I can add protection for this in the workbench but it appears that somehow a recipe is invalid because it is not finding a recipe where it should. I'll fix it on my side though
