### ISSUE TITLE
Higher value support?

### ISSUE THREAD

**Issue by PessimisticBastard** [McJty/RFToolsControl#111]
I'm trying to use a processor in place of a power monitor for 1.12.1, since Ender IO doesn't exist for it yet. I'm using a Mekanism Induction Matrix, and running into the high values issue. The highest value for the processor is 2,417,483,647, while the Matrix can hold 3,200,000,000. This obviously creates problems when trying to get the actual amount. Could you add support for higher values?

Edit: While I'm thinking of it, any chance for decimal support?

**Comment by McJty** [comment]
This is currently not very easy to do I'm afraid. But I'm not closing this as it might be interesting in the future

**Comment by pyure** [comment]
I would also like to see both suggestions above implemented, although I believe they warrant separate issues.

**Comment by McJty** [comment]
Implemented in next release
