### ISSUE TITLE
Can't fetch from Storage Scanner

### ISSUE THREAD

**Issue by tofof** [McJty/RFToolsControl#117]
Program: https://gist.github.com/tofof/c0191fcaf0afebb89dd1d641efc9ef77 
Images: https://imgur.com/a/hKiyL
Note: routable or not on chest makes no difference.

Simple program - on redstone, pull a cobblestone from the inventory to the north of the processor.

Chest to the north? Works as expected.
Storage scanner (with a chest with cobble visible in the scanner) to the north? Pulls nothing.

Similarly,
GetIngredientsSmart - can't pull ingredients from a scanner that sees the ingredients.
CountItemExternal - returns a count of 0 when the storage scanner sees 100+.

I very much expected storage scanners to work: 1) the "Fetch Items" opcode explicitly states "Also works for a storage scanner system", 2) using a scanner instead of a chest was the [workaround solution](https://github.com/McJty/RFToolsControl/issues/88#issuecomment-308260961) to issue #88.
> I "fixed" it by using a storage scanner block that has the real chest as its inventory, then instead of specifying the real chest in the program, used the storage scanner item in the processor.

From that quote it seems pretty clear he means the storage scanner and not modular storage, since "having the real chest as its inventory" only makes sense for the storage scanner.

Test environment uses only the following (no modpacks, no other mods):
Minecraft 1.10.2
forge-1.10.2-12.18.3.2511
compatlayer-1.10-0.2.9
mcjtylib-1.1x-2.5.0
rftools-1.1x-7.14
rftoolsctrl-1.1x-1.6.9 and rftoolsctrl-1.1x-1.7.0 (same behavior in both)

**Comment by McJty** [comment]
Do you have an rftools storage module in your processor? That is required for this feature to work. i.e. a storage module (the same one that is also used for screens) linked to the storage scanner must be present in the processor. You don't even have to set direction. The access is remote through that storage module that has to be present in the processor

**Comment by tofof** [comment]
Nope, I sure didn't. Thanks. Works great now.
