### ISSUE TITLE
the signal command and interaction screen module

### ISSUE THREAD

**Issue by ghost** [McJty/RFToolsControl#124]
Im still learning how rftools control works and i cant find out how the signal command and interaction screen module works or if it even works, it could also be a problem with the modpack itself (Revelation) but because i haven't found any tutorials where the show the signal command or the interaction module i at least want to ask.

What i have done: programm card with event message with the name "test" and connected to an logmessage opcode. Then in the processor with a cpu and the program card in it (and power)  i tipped the command "signal test" which should as i hoped start the program (it didn't). Nor was i able to get the interaction screen module to work, as i guess(don't exactly now how the program works) it sends a signal to the chosen processor, like it would with "signal test" if i chose in the module as signal "test". I hope someone could help me out, if this post is useless or shouldn't be here just delete it but would love to know. (btw great mod have so much fun playing with it :3 )

**Comment by josephcsible** [comment]
You need to use "event: signal" to respond to signals, not "event: message".

**Comment by ghost** [comment]
oh thanks with this it works.
If i may ask: Is there or will there be an approved video about the rftools control mod showing ALL the events, opcodes in general how the whole mod works? I think it would help if there were just a video link in the wiki showing everything.

**Comment by josephcsible** [comment]
There's [McJty's introduction video](https://www.youtube.com/watch?v=0a2-9O-8HbM) and Direwolf20's spotlight ([part 1](https://www.youtube.com/watch?v=18-R5L-CATg), [part 2](https://www.youtube.com/watch?v=EOmXRi3RyWk), and [part 3](https://www.youtube.com/watch?v=tQsV8Lh7KxY)). In addition, the in-game documentation book is generally the most up-to-date source.
