### ISSUE TITLE
[Question] Is it indented that multi-step crafting cannot work with only one CPU

### ISSUE THREAD

**Issue by hnOsmium0001** [McJty/RFToolsControl#126]
##### Issue description: 
Recently I've trying to work with auto craft of RFTools Control, and for about 2 hours I'm struggling with multi-step crafting stop working. And after I insert four CPU in total, it start working.

##### Steps to reproduce: 
1. Build a same autocrafting program with the one on the video "Recursive autocrafting with RFTools Control";
2. Processor with one CPU (all levels are ok), network card, storage control screnn module bond to a scanner with material in it;
3. Workbench, pattern chest (can be workbench itself), dump chest to storage scanner;
4. Setup recipes that need multi steps to complete (e.g. Craft gold nuggets first than machine frame);
5. Click on items in crafting station;

![2018-06-02_21 01 38](https://user-images.githubusercontent.com/36975818/40883019-4b148a68-66a8-11e8-813e-da220cecfe90.png)
![2018-06-02_21 01 43](https://user-images.githubusercontent.com/36975818/40883020-4b2c4fd6-66a8-11e8-898d-7d8a69731f6c.png)
![2018-06-02_21 02 00](https://user-images.githubusercontent.com/36975818/40883021-4b4100ac-66a8-11e8-86da-1122318707fc.png)
![2018-06-02_21 02 10](https://user-images.githubusercontent.com/36975818/40883022-4b5689c2-66a8-11e8-8f7b-f7281a28b6da.png)
*the two redstone events is just for test if lock is on and reset it*

##### Versions:
* Minecraft: 1.12.2
* Forge: 14.23.3.2698
* McJtyLib: 2.6.7
* RFTools: 7.33
* RFTools Control: 1.8.1

**Comment by McJty** [comment]
Yes you need multiple cpu's for multiple levels. That cannot be avoided

**Comment by hnOsmium0001** [comment]
Thanks!
