### ISSUE TITLE
Bug: Pop item from vector returning an empty vector all the time

### ISSUE THREAD

**Issue by nicro950** [McJty/RFToolsControl#128]
https://github.com/McJtyMods/RFToolsControl/blob/c7c20737df1e4bafdde8050e5e265346e4259b04/src/main/java/mcjty/rftoolscontrol/logic/registry/Opcodes.java#L1906

Looks like the new vector will always have a size of zero, since an empty list always have a size of zero. This is verified ingame, where "pop items from vector" always returns an empty vector.

Also looks like someone has submitted a pull request with the fix: #90

**Comment by McJty** [comment]
Fixed for next version
