### ISSUE TITLE
Highlight unreachable "code"

### ISSUE THREAD

**Issue by MaPePeR** [McJty/RFToolsControl#13]
maybe tint the them red or add a giant cross or questionmark to them.

**Comment by McJty** [comment]
You know about the 'Val' button in the programmer? Also you can then doubleclick on those lines

**Comment by MaPePeR** [comment]
I think the validation should just always be present, so you find errors as soon as possible. 
Its one of the main benefit that modern IDEs provide: automatic and on the fly evaluation of code to show errors where they arise as soon as possible.

And the button is not really prominent and new users probalby don't know what it does and that they should press it as part of your workflow. (I didn't)
I think a "in code" highlighting of errors might reduce the entry barrier into creating programs.

**Comment by McJty** [comment]
I could do that but I want to do it in a non-obtrustive way as I often have lots of unreachable code segments that I set aside for later use. I wouldn't want all of those opcodes to constantly flash or something

**Comment by MaPePeR** [comment]
constantly flashing is not an option, i agree.

My list of suggestions:
* Exklamation mark in top right corner
* Tint the whole code-piece in a color
* overlay the code-piece with a red X
* Red Border around the code piece (i think this might not be noticed good enough)

**Comment by McJty** [comment]
I could put an exclamation mark in the 'Val' button at least. That would give some hint that that has to be pressed. But I'll consider the other options too

**Comment by McJty** [comment]
Implemented in next release
