### ISSUE TITLE
Server crash by "ProgException: Too many events"

### ISSUE THREAD

**Issue by marcin212** [McJty/RFToolsControl#14]
log: http://pastebin.com/raw/HDcGaPYk
rftoolscontrol 1.3.3

**Comment by McJty** [comment]
Ok, interesting bug. The exception is caused because there are too many queued events (probably too few cores in your processor). But the problem is that an exception itself also causes an event. I'll fix this somehow

**Comment by McJty** [comment]
Fixed next release
