### ISSUE TITLE
Server Instant crash

### ISSUE THREAD

**Issue by walker-dev** [McJty/RFToolsControl#141]
* RFTools Control: 1.9.3
[crash log](https://gist.githubusercontent.com/boosterdev/ce26f85e17966c6972466367235ad2fd/raw/af0b20a4d4b60a40ffab0141b62dbe8f935e0ddb/gistfile1.txt)

**Comment by josephcsible** [comment]
Why do you think this is related to RFTools Control? It looks to me like it's actually caused by one of your coremods. See if you can reproduce the problem with no coremods.

**Comment by walker-dev** [comment]
[here you go](https://gist.githubusercontent.com/boosterdev/9b784e01405fc9d702a737f627b68ae6/raw/f82dbb4559da24271f4d8b082d9780a0a76570f5/gistfile1.txt)
To me it looks like RFtools Control
When I remove ftoolsctrl from the list it just starts normaly

**Comment by walker-dev** [comment]
https://github.com/McJtyMods/McJtyLib/commit/c74e7e26fb0d9d90ec2abc023cac4de325ecdeb8

**Comment by ghost** [comment]
@boosterdev its Rftools Control, its throwing the same error on me

**Comment by josephcsible** [comment]
Okay, looking at the new log makes it clear. It wasn't at all clear when you had 300 mods.

**Comment by walker-dev** [comment]
Updating to mcjtylib 3.1.1 fixed the problem
