### ISSUE TITLE
Reading Draconic Energy Core

### ISSUE THREAD

**Issue by PessimisticBastard** [McJty/RFToolsControl#145]
Issue description: I'm currently using an RF Tools screen to read the amount of energy coming in and the total stored energy, and it's working just fine.  However, the controller reads "No RF Support" when trying to read the core and using the "long" get rf in machine option, but reads just fine when using the "interger" get rf in machine option. Both the controller and the screen card are using an energy pylon as a basis.

Steps to reproduce: Place controller near energy pylon, place in program in controller, get above results.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2811
* CompatLayer (only if on Minecraft 1.10 or 1.11): N/A
* McJtyLib: 1.12-3.1.1
* RFTools: 1.12-7.61
* RFTools Control: 1.12-1.9.3

Possibly incompatible mods and versions: N/A

Relevant logs, if any: N/A

**Comment by josephcsible** [comment]
Draconic Evolution made up its own way to handle 64-bit power instead of using TESLA (the standard 64-bit power API). There's nothing we can do on our end. You'll need to get them to support TESLA on their end.
