### ISSUE TITLE
Rftools Dimension (Server) crash!

### ISSUE THREAD

**Issue by ViertelForRF** [McJty/RFToolsControl#146]
Issue description:  Hey fellas, im new here but i've run into a bug with rftoolsdimensions. So im trying to setup a server with the template from FTB revelation and added some other mods. So now the Server wont start, so im trying my luck here to find help. If you need anymore information then below, tell me.
As said ill link my crash log here:
CRASH LOG: https://pastebin.com/5LE4pKuA
LOG: https://pastebin.com/qQ49Zdyc

But here is the line in the crash that is importend (I think atleast)

[10:20:58] [Server thread/ERROR] [FML]: An error occurred trying to load an EventBusSubscriber mcjty.rftoolscontrol.proxy.CommonProxy for modid rftoolscontrol

Steps to reproduce: 
-
dont think this  needs to be done, if so tell me.

Versions:
* Minecraft: 1.12.2
* Forge: forge-14.23.5.2796
* CompatLayer (only if on Minecraft 1.10 or 1.11): -
* McJtyLib: mcjtylib-1.12-3.1.0
* Rftools Dimensions: rftoolsdim-1.12-5.64
* RFTools: rftools-1.12-7.60
* RFTools Control: rftoolsctrl-1.12-1.9.3

-

Above

**Comment by ViertelForRF** [comment]
Also , i think in the crash log are the mods listed.
The mods i added after are:
VeinMiner-1.12-0.38.2.647+b31535a
Cucumber-1.12.2-1.1.3
EnchantingPlus-1.12.2-5.0.176
LycanitesMobsComplete+1.20.5.0+[1.12.2]
elementaldimensions-1.12-0.3.2
thaumictinkerer-1.12.2-5.0-353c71c
Mekanism-1.12.2-9.4.13.349
MysticalAgriculture-1.12.2-1.7.1

**Comment by Ommina** [comment]
Update your mcjtylib to 3.1.1 -- https://minecraft.curseforge.com/projects/mcjtylib/files/2660396

As an aside, I expect you will struggle mightily trying to run that many mods with 2GB allocated memory.  Be on the watch for Out of Memory / Out of Heap Space crashes.

**Comment by ViertelForRF** [comment]
Alright, ive updated it and started the server and the client (takes a long time with my setup ;) ) and the Server doesnt crash anymore so ill say thank you for that. But the problem now is that im getting an error message when im trying to connect. DAMN.
https://pastebin.com/zq85Anmr

**Comment by ViertelForRF** [comment]
also worth noting: (hope this works) 

![bandicam 2019-02-24 11-23-34-045](https://user-images.githubusercontent.com/47939578/53297967-a8001080-3826-11e9-9f28-68dcfe8124ba.jpg)

**Comment by McJty** [comment]
That last error doesn't seem related to any of my mods

**Comment by ViertelForRF** [comment]
yeah i think ill try to remove applied energ. and see what is does then ;)

**Comment by Ommina** [comment]
Well, we're very much off-topic for the RFToolsControl issue tracker now, as your original crash has been resolved.  It's probably best to close this one up.

That said, while I make no promises, check your config files for mystical agriculture.  Ensure that crops related to AE2 (certus quartz, fluix come to mind) are disabled.

But we really off off-topic with this.

**Comment by ViertelForRF** [comment]
True alright how do i mark this as solved?
