### ISSUE TITLE
Slot > Item - Intended or Bug?

### ISSUE THREAD

**Issue by ftog-thorgal** [McJty/RFToolsControl#15]
Version used: rftoolsctrl-1.10-1.3.3
Using "Eval: count items external" on an adjacent vanilla chest.
When you set "Item:" to Stone and leave the "Slot:" empty it will work properly, meaning it will return an integer for all Stone found in the chest, and 0 if there is no Stone in the chest.
When you set "Item:" to Stone and set "Slot:" to 0 - so I only want to count slot 0 when it has Stone - it always returns the amount in slot 0 regardless of what the item is disregarding the Item setting.

I was just wondering if this is working as intended that Item is ignored when Slot is set? If it is, then I think it should be reflected in the tooltip of the Slot and Item fields.

**Comment by McJty** [comment]
Good catch. I'll see which solution I will follow. Probably it doesn't have to ignore the item

**Comment by McJty** [comment]
Fixed next release. The item will not be ignored even if a slot is given
