### ISSUE TITLE
[Question/Suggestion] Ability to automate saving programs in programmer

### ISSUE THREAD

**Issue by Drethic** [McJty/RFToolsControl#150]
Issue description: 
I am trying to setup a large number of Draconic Evolution Reactors (64 to test) using a set of 7 programs.  I have 7 programmers setup each with their own programs but I'd like to be able to feed a chest of blanks program cards in and have it save and deposit into an output chest.  Is there a way to automate this process or can I request this as a feature.

Additional QoL improvements to the programmer:
1) Auto-focus the `Card name:` window when you save a fresh card or change the existing card name
2) Allow copy/paste to and from the `Card name:` window.  Currently if you have text on your clipboard the field doesn't know how to read it and you get `Error reading from clipboard`

Steps to reproduce:
Setup 64 reactors needing 7 cards each and having to save 448 programs :)

Versions:
* Minecraft: 1.12.2
* Forge: forge-14.23.5.2808
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.12-3.1.1.jar
* RFTools: rftools-1.12-7.61.jar
* RFTools Control: rftoolsctrl-1.12-1.9.3.jar

Possibly incompatible mods and versions:
N/A

Relevant logs, if any: 
N/A

**Comment by McJty** [comment]
In the next version the programmer will save the program to the card it contains if it is given a redstone signal. That should allow automation for this
