### ISSUE TITLE
 Invocation Target Exception (Caused by "ModLoadingException: RFToolsControl has class loading errors") 

### ISSUE THREAD

**Issue by Twisted-Code** [McJty/RFToolsControl#169]
Issue description: Crash (class loading errors, apparently)

Steps to reproduce: Not entirely certain but it seems to be a conflict with something in my [curseforge modpack](https://www.curseforge.com/minecraft/modpacks/puncher-pack-6-golden-carrot-edition). I plan to do some more troubleshooting tomorrow, and will let you know what I turn up. 

Versions:
* Minecraft: 1.15
* Forge: 31.2.36
* ~~CompatLayer (only if on Minecraft 1.10 or 1.11):~~ N/A
* McJtyLib: 1.15-4.1.7
* RFTools: 1.15-1.1.6
* RFTools Control: 1.15-3.0.8

Possibly incompatible mods and versions: none known

Relevant logs, if any: 
[most recent crash report](https://gist.github.com/macks2008/643611fbccaf20628a61d45702162d49)

**Comment by McJty** [comment]
Your McJtyLib is too old. Update all my mods to latest and it should be fine

**Comment by Twisted-Code** [comment]
ah. Okay. Will give that a try. Thanks!
(Stay tuned in case that actually isn't the only problem? edit: it was the only problem)
