### ISSUE TITLE
Uable to use the "Drop Item"

### ISSUE THREAD

**Issue by FeedTheChunk** [McJty/RFToolsControl#180]
Issue description: Unable to pick up any item from inventory to use in the "Drop item:" feature for Item OpCodes.

Steps to reproduce: 
Open Programmer, insert a Program Card, place any item opcode (i.e. Operation: fetch items), select "Item."  In the configuration window select "Constant."  It's my understanding that from here you should be able to drag an item from your inventory and drop on the Drop Item place provided.  However, unable to pick up any item from inventory to drag and drop to the configuration slot.

I have tried with all of the item Opcodes that take an "Item" as a config parameter, all seem to be affected.

Versions:
* Minecraft: 1.16.4
* Forge: 35.1.37
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.16-5.0.16
* RFToolsbase :1.16-2.0.9
* RFTools Control: 1.16-3.0.8

Using the SkyBees mod pack version 3.0.3b

Possibly incompatible mods and versions: 
OptiFine HD U G7 - Disabling had no affect.
Performant 1.16.2-4-3.30m is also included in the pack but has been disabled.

Relevant logs, if any: None.

![image](https://user-images.githubusercontent.com/35508630/110040068-cf3c2300-7d07-11eb-9597-d3bfe6632d08.png)

**Comment by McJty** [comment]
Ok, I can reproduce. Will try to find a fix

**Comment by McJty** [comment]
Will be fixed soon. Needs an update of McJtyLib, RFToolsBuilder, and RFToolsControl

**Comment by FeedTheChunk** [comment]
Thank you for looking at this. Now I know it isn't something I was doing wrong.
