### ISSUE TITLE
Can´t place Storage Screen Module into Processor

### ISSUE THREAD

**Issue by carLos186** [McJty/RFToolsControl#181]
Issue description: Can´t place Storage Screen Module into Processor

Steps to reproduce: 
craft a storage screen module and try to place it into the processor.

Versions:
* Minecraft: 1.16.5
* Forge: 36.0.42
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.16-5.0.16
* RFTools: 1.16-2.0.10
* RFTools Control: 1.16-4.0.7

**Comment by carLos186** [comment]
It is also not possible to click and select items while the item menu is shown
![image](https://user-images.githubusercontent.com/34027706/110106500-0b27c480-7daa-11eb-9c1a-26c186f64a77.png)

**Comment by The--Captain** [comment]
Same.

Versions:

Minecraft: 1.16.5
Forge: 36.1.4
McJtyLib: 1.16-5.0.19
RFTools: 1.16-2.0.10
RFTools Control: 1.16-4.0.8

**Comment by McJty** [comment]
Where in the processor are you trying to place it?

**Comment by McJty** [comment]
Never mind, fixed

**Comment by The--Captain** [comment]
Anywhere in the 4x4 grid, where the network card, ram, and cpus go.  I've built fully automated factories with RFtools processors, just not this particular version combo.  It's definitely not letting me put the storage screen 
module in where it has in other versions.

![rftools_bug1](https://user-images.githubusercontent.com/4986916/118347634-5d076c00-b50a-11eb-9f28-b039da0d9f5e.png)

**Comment by The--Captain** [comment]
Wow, that was fast! :-D

**Comment by The--Captain** [comment]
Does this fix require updating RFtools Control, or McJtyLib (or both)?

**Comment by McJty** [comment]
Just RFTools Control (unless you have old versions of all those mods)

**Comment by The--Captain** [comment]
Can confirm updating to RFTools Control 1.16-4.0.9 fixes this issue.

Thanks!

**Comment by The--Captain** [comment]
Excellent mod collection, BTW.  I always feel I have "won" Minecraft when I get my RFTools Control factory working, which basically allows me to hit a single button in the crafting station to create anything, which winds up being close enough to creative mode inventory (just a slight wait for the redundant crafting is the only real difference).
