### ISSUE TITLE
Vector screen bug

### ISSUE THREAD

**Issue by HRJDragon** [McJty/RFToolsControl#183]
Issue description: screen not correctly displaying vector art with vector art module when the corresponding processor can display it proving the code is working

Steps to reproduce: program card programed with vector art opcodes that when inserted into a powered, graphics + network + cpu processor displays the graphic on the overhead display. However when vector art module shift clicked onto processor and inserted into a powered empty screen the screen goes black and does not respond. 

Versions:
* Minecraft: 1.16.5
* Forge: 36.1.16
* McJtyLib: 1.16- 5.0.19
* RFTools: rftools base: 1.16- 2.0.10
* RFTools Control: 1.16- 4.0.8

Atm6 base modpack

Possibly incompatible mods and versions: unsure

**Comment by McJty** [comment]
Fixed in the next release of RFTools Utility and RFTools Control
