### ISSUE TITLE
Processor cannot fetch items from storage

### ISSUE THREAD

**Issue by SkorpioSound** [McJty/RFToolsControl#194]
Issue description: The processor's "fetch items", "get ingredients" and "get ingredients smart" opcodes are all unable to move items from a linked Storage Scanner's storage system. The "count items external" opcode DOES still work and can count specific items in the storage system.

Steps to reproduce: create a program in the processor that attempts to fetch items from a linked Storage Scanner's system. Nothing will happen.

Versions:
* Minecraft: 1.19.2
* Forge: 43.2.3
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 7.1.1
* RFTools: 4.1.1
* RFTools Control: 6.1.0

Possibly incompatible mods and versions: 

Relevant logs, if any: 

EDITED TO ADD:

Additionally, the "fetch" opcode doesn't appear to be able to pull crafting results from the Workbench. Hoppers and pipes CAN pull from the underside of the Workbench so I'd assume it's an issue with the "fetch" opcode.

**Comment by SkorpioSound** [comment]
Additionally, the "fetch" opcode doesn't appear to be able to pull crafting results from the Workbench. Hoppers and pipes CAN pull from the underside of the Workbench so I'd assume it's an issue with the "fetch" opcode.

**Comment by McJty** [comment]
Fixed
