### ISSUE TITLE
Crash when selecting "gfx" in processor

### ISSUE THREAD

**Issue by diefesson** [McJty/RFToolsControl#197]
Issue description: 

Steps to reproduce:

1. select "gfx" in processor
2. games crashes
3. World becomes unacessible as crash happens again when loading

Versions:
* Minecraft: 1.20.1
* Forge: 47.3.0 (recommended), 47.3.10 (latest)
* NeoForge: 47.1.106 (latest)
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 8.0.6
* RFTools: 5.0.5
* RFTools Control: 7.0.2

Possibly incompatible mods and versions: No other mods beside RFTools * mods, all on latest version

Relevant logs, if any: 
General log: https://mclo.gs/uxuPU0d
Crash log: https://mclo.gs/NFMsKpn

**Comment by BeepSterr** [comment]
Just ran into this too, it's a nasty one

**Comment by AntonTakk** [comment]
Same here, on an server, only the client crashes. anyone not near it can still login/play just fine. but if you get to close your client crashes and you can't successfully re-join until an admin teleports you away.  lowering render / sim distance may allow you to get closer

**Comment by McJty** [comment]
Fixed in 7.0.3 of RFTools Control
