### ISSUE TITLE
[1.10-1.5.0] Fluid disappear

### ISSUE THREAD

**Issue by marcin212** [McJty/RFToolsControl#20]
Video: https://youtu.be/1P-Wkkl4w-0
Tested on SMP

**Comment by McJty** [comment]
I'll check it out

**Comment by worblood** [comment]
I have a similar problem, I can't get the "push liquid" opcode to work at all. No liquids being pushed, no error message.

**Comment by McJty** [comment]
To @worblood, on what tank are you having this? EnderIO tank need a side to access too. I think your issue might be different from the first issue

**Comment by McJty** [comment]
Fixed in 1.5.1
