### ISSUE TITLE
overwriding variables causes issue

### ISSUE THREAD

**Issue by redgoblin88** [McJty/RFToolsControl#23]
i am trying to create it so that the controller can read the amount of RF in a copacitor bank and output it to a screen, so i created:
a repeat event (20 ticks) that leads into 
"eval:get RF in machine" on the south side with above access, this is then
written to "variable 0" using the "operation: set variable"
with this variable set, it goes into a "gfx text" with an id: "power", location: "50, 50", text:":0", color:"-16776961" (hex:$FF33CC33)
after it has outputted the information, it waits 20 ticks (i dont want it every tick ;) )
then it loops back to the "get RF in machine" but this is where the issue arises

when i was debugging i noticed that i could overwride it, so i added two  extra opcodes between the wait and the "get RF" which are:
eval: integer, value "0"
operation: set variable "variable 0"

with the location i put it, the error i am getting is "internal error" and the co-ords that ity points to is the "operation set value"

upon testing in debug mode i notice that if variable 0 is set to null (0), it goes through the first loop but the second time when it tries to overwride it fails, even with AND without the extra two that i mentioned above. the variable tha tis set is "907637" but i cant see how that can be too big as the first time it sucesfully writes to the screen.

the following screenshot is what i have got (ignore the top as that is only drawing a GUI which does work)

![2016-11-05_14 16 19](https://cloud.githubusercontent.com/assets/13396472/20030770/b75ee9ca-a363-11e6-91a4-c97546ce8998.png)

**Comment by McJty** [comment]
Could you do ctrl-a/ctrl-c and paste me the code in text form? Thanks

**Comment by redgoblin88** [comment]
forgot that was a thing... here you go:

[
  {
    "pos": {
      "x": 0,
      "y": 0
    },
    "opcode": {
      "id": "ev_rs_on",
      "primary": "R",
      "parameters": [
        {
          "type": "side",
          "value": {
            "side": "east"
          }
        },
        {
          "type": "boolean",
          "value": {
            "null": true
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 2,
      "y": 2
    },
    "opcode": {
      "id": "do_setvar",
      "primary": "D",
      "parameters": [
        {
          "type": "integer",
          "value": {
            "var": 0
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 1,
      "y": 2
    },
    "opcode": {
      "id": "eval_getrf",
      "primary": "R",
      "parameters": [
        {
          "type": "inventory",
          "value": {
            "side": "south",
            "intside": "up"
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 2,
      "y": 3
    },
    "opcode": {
      "id": "do_text",
      "primary": "D",
      "parameters": [
        {
          "type": "string",
          "value": {
            "v": "power"
          }
        },
        {
          "type": "tuple",
          "value": {
            "x": 50,
            "y": 50
          }
        },
        {
          "type": "string",
          "value": {
            "var": 0
          }
        },
        {
          "type": "integer",
          "value": {
            "v": -16776961
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 0,
      "y": 2
    },
    "opcode": {
      "id": "ev_timer",
      "primary": "R",
      "parameters": [
        {
          "type": "integer",
          "value": {
            "v": 20
          }
        },
        {
          "type": "boolean",
          "value": {
            "null": true
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 1,
      "y": 3
    },
    "opcode": {
      "id": "do_setvar",
      "primary": "U",
      "parameters": [
        {
          "type": "integer",
          "value": {
            "var": 0
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 2,
      "y": 4
    },
    "opcode": {
      "id": "do_delay",
      "primary": "L",
      "parameters": [
        {
          "type": "integer",
          "value": {
            "v": 20
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 1,
      "y": 4
    },
    "opcode": {
      "id": "eval_integer",
      "primary": "U",
      "parameters": [
        {
          "type": "integer",
          "value": {
            "v": 0
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 8,
      "y": 0
    },
    "opcode": {
      "id": "do_line",
      "primary": "R",
      "parameters": [
        {
          "type": "string",
          "value": {
            "v": "ge"
          }
        },
        {
          "type": "tuple",
          "value": {
            "x": 5,
            "y": 45
          }
        },
        {
          "type": "tuple",
          "value": {
            "x": 125,
            "y": 45
          }
        },
        {
          "type": "integer",
          "value": {
            "v": -65536
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 7,
      "y": 0
    },
    "opcode": {
      "id": "do_line",
      "primary": "R",
      "parameters": [
        {
          "type": "string",
          "value": {
            "v": "gd"
          }
        },
        {
          "type": "tuple",
          "value": {
            "x": 5,
            "y": 35
          }
        },
        {
          "type": "tuple",
          "value": {
            "x": 125,
            "y": 35
          }
        },
        {
          "type": "integer",
          "value": {
            "v": -256
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 6,
      "y": 0
    },
    "opcode": {
      "id": "do_line",
      "primary": "R",
      "parameters": [
        {
          "type": "string",
          "value": {
            "v": "gc"
          }
        },
        {
          "type": "tuple",
          "value": {
            "x": 5,
            "y": 25
          }
        },
        {
          "type": "tuple",
          "value": {
            "x": 125,
            "y": 25
          }
        },
        {
          "type": "integer",
          "value": {
            "v": -13382605
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 5,
      "y": 0
    },
    "opcode": {
      "id": "do_line",
      "primary": "R",
      "parameters": [
        {
          "type": "string",
          "value": {
            "v": "gb"
          }
        },
        {
          "type": "tuple",
          "value": {
            "x": 125,
            "y": 25
          }
        },
        {
          "type": "tuple",
          "value": {
            "x": 125,
            "y": 45
          }
        },
        {
          "type": "integer",
          "value": {
            "v": -1
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 4,
      "y": 0
    },
    "opcode": {
      "id": "do_line",
      "primary": "R",
      "parameters": [
        {
          "type": "string",
          "value": {
            "v": "ga"
          }
        },
        {
          "type": "tuple",
          "value": {
            "x": 5,
            "y": 25
          }
        },
        {
          "type": "tuple",
          "value": {
            "x": 5,
            "y": 45
          }
        },
        {
          "type": "integer",
          "value": {
            "v": -1
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 3,
      "y": 0
    },
    "opcode": {
      "id": "do_text",
      "primary": "R",
      "parameters": [
        {
          "type": "string",
          "value": {
            "v": "tb"
          }
        },
        {
          "type": "tuple",
          "value": {
            "x": 100,
            "y": 5
          }
        },
        {
          "type": "string",
          "value": {
            "v": "Reset"
          }
        },
        {
          "type": "integer",
          "value": {
            "v": -16711681
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 2,
      "y": 0
    },
    "opcode": {
      "id": "do_text",
      "primary": "R",
      "parameters": [
        {
          "type": "string",
          "value": {
            "v": "ta"
          }
        },
        {
          "type": "tuple",
          "value": {
            "x": 5,
            "y": 5
          }
        },
        {
          "type": "string",
          "value": {
            "v": "Reactor"
          }
        },
        {
          "type": "integer",
          "value": {
            "v": -1
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 1,
      "y": 0
    },
    "opcode": {
      "id": "do_gfx_clear",
      "primary": "R",
      "parameters": [
        {
          "type": "string",
          "value": {
            "null": true
          }
        }
      ]
    }
  }
]

**Comment by McJty** [comment]
Is that card the only one in the processor?

**Comment by redgoblin88** [comment]
yes, its the only one in the first slot. it has been given a RAM chip, b500 CPU and a graphics card.

the first slot has access to three constants which the first (0) does seem to be getting the correct value the first run, but it doesnt change as the bug occurs

![2016-11-05_15 11 02](https://cloud.githubusercontent.com/assets/13396472/20031087/0ef5ea2a-a36a-11e6-9dce-e54a2e192c17.png)

**Comment by McJty** [comment]
When there is an internal error it will have shown a more complete exception in the log somewhere.

Can you give that to me?

Also, what version of RFTools Control?

**Comment by redgoblin88** [comment]
i am using version: 1.5.1 and i am unsure wher eto find the "more coml;ete log" as the consiol doesnt output anything, but the debug with steps does this:
![2016-11-05_15 14 01](https://cloud.githubusercontent.com/assets/13396472/20031133/a4c90c4e-a36a-11e6-8be7-807a0abe66b5.png)

**Comment by McJty** [comment]
Well complete log is in the 'logs' folder of your minecraft instance

**Comment by redgoblin88** [comment]
here: http://pastebin.com/re2Wskr8

i used the latest.log

**Comment by McJty** [comment]
It is actually a bug in your own code. For setvar you should not use a variable but a constant. i.e. the variable is an index and so you should use 'constant' 0 for variable 0
