### ISSUE TITLE
Processor command line issues

### ISSUE THREAD

**Issue by UnlimitedHugs** [McJty/RFToolsControl#29]
* Closing the processor UI will submit the typed command even when Enter is not pressed.
* Using the up arrow to get the last used command produces unexpected results. How to reproduce:
1. Type "help", submit
2. Type "list", submit
3. Press up arrow, submit
4. Press up arrow, see "help" show up

**Comment by McJty** [comment]
I'll fix the first issue.

As to the second issue, that's how it is supposed to be. The up/down arrows give you a kind of history to scroll though.

**Comment by UnlimitedHugs** [comment]
The thing with issue 2 is that console applications will generally give you the last used command when pressing the up arrow. Also, when stepping through a program in debug mode you have to use the sequence "up, down, enter" to make one step.
But it's your call, of course.

**Comment by MaPePeR** [comment]
The history is working in a weird way, though. Look at the example given:

1. Execute help
2. Execute list (this is now the last executed command) 
3. Press up and submit. Executes list again. 
4. Press up again does NOT execute list again, but help. Even though list was the command that was  executed before. 

So to fix this you need to move to the bottom of the history after a command has been executed.

**Comment by McJty** [comment]
Well I don't think that's weird at all. That's how I programmed it to work :-)
If you do up and submit you execute list again. But you are still at that position in the history. So if you press up again you go to the older one in the history
