### ISSUE TITLE
Auto Crafting

### ISSUE THREAD

**Issue by TonRZN** [McJty/RFToolsControl#3]
The crafting recipes available isn't showing on the crafting station and the pattern can only handle one item, also when you put a normal recipe it doesn't show automatically on the output.
I don't know if it's supposed to behave this way
Just one more thing: WHen the remote crafting station will be available ?

**Comment by McJty** [comment]
The pattern can handle more items if you feed it through JEI (i.e. fill the pattern with JEI + button)

And it is also normal and how it should be that it doesn't show output with normal recipe as you may actually want another result based on ingredients. i.e. with the crafting card you can make a recipe for going from oak logs directly to fences. With only one crafting card

Remote crafting station will be ready when I implement it :-)

**Comment by TonRZN** [comment]
I mean, like for processing patterns, I can put more items into the input slot (a bigger stack size), the JEI + only works with normal crafting table recipes, right ?

**Comment by McJty** [comment]
yes it does and yes I'm aware of the limitation that if you manually insert items you cannot set an amount. I haven't yet found out a way to fix that though

**Comment by TonRZN** [comment]
Ah, okay, but really cool mod, good work as always, thanks for your patience

**Comment by McJty** [comment]
Fixed next release
