### ISSUE TITLE
[Bug] Moving Liquid crystal out of multitank

### ISSUE THREAD

**Issue by Unadvoidable** [McJty/RFToolsControl#32]
**Setup**
Modpack:    Direwolf20 v1.1.1
RF Control:  v1.5.2
DR:              v1.3.1

**Problem**
I can move Liquid Crystal into the multitank, but i cannot move it out of the multitank. Still executes the program block and writes the following text block.

[refill_meltet.txt](https://github.com/McJty/RFToolsControl/files/631359/refill_meltet.txt)
![image](https://cloud.githubusercontent.com/assets/4508203/20889151/3654fef8-bb02-11e6-8ec5-90149ad9e0df.png)
![image](https://cloud.githubusercontent.com/assets/4508203/20889246/8d5a9474-bb02-11e6-8964-ff231dd7d7b0.png)

**Comment by McJty** [comment]
I see only one fetchliquid from node 'smeltet'. Is that the multitank? Because that one is accessing down and there is no node above the multitank so I think something is wrong with your program

**Comment by Unadvoidable** [comment]
I'll attach a labeled picture and walk you throu it.
ps. Has even problem getting me the Amount of the liquid in the Tank if not in the first physical slot (not liquid variable slot ) (eval liquid in tank). How does that even work with multitank when i check eg. Up and there are 3 fluids inside?

**Program**
- Check if there is a crystal worth of liquid inside the purifier (6000mb),
- calculate how much is missing and save that in var0
- check if we have the needed amount inside the multitank (failsafe)
- if not, check if there is enough in the smelter and move that into multitank and the into purifier
- if not "melt more"

Ps. This "Exact" method works with the lava refill programm/ other std fluids, ill attach that too.
[lava_refill.txt](https://github.com/McJty/RFToolsControl/files/631471/lava_refill.txt)

![2016-12-05_15 47 45](https://cloud.githubusercontent.com/assets/4508203/20890046/c8dd15c8-bb05-11e6-9c04-799b9d0cfa1f.png)
![2016-12-05_16 04 28](https://cloud.githubusercontent.com/assets/4508203/20890048/c8e15016-bb05-11e6-94c5-34752c0a07cc.png)
![2016-12-05_16 04 31](https://cloud.githubusercontent.com/assets/4508203/20890047/c8ddf114-bb05-11e6-9e19-6a6917c2e342.png)

**Comment by McJty** [comment]
Oh I see the problem! You cannot access multitanks like that. A multitank is always adjacent to a processor and the liquids in the multitank are 'internal' and only accessible through the slots. You cannot access them like you're trying to do. Just use the internal tank slots which are directly connected to the multitank

**Comment by Unadvoidable** [comment]
Updated my description a little bit, you're too fast m8 ;-)

No i always go through the Multitank and use it as the temp_fluid_buffer. I'm not trying to move from smeltet->purify directly, i'd "rtmf".

**Problems**
1.  [get_fluid_in_tank] only returns first slots content of multitank (as far as i tested), hence the 2nd Tank on top to circumvent that.
2. The Liqid crystal had been moved into the tank correctly, but cannot been moved out (proves that slot variable configuration is correct)

or are we talking past each other?

**Comment by McJty** [comment]
I'm totally not following anymore. Can you make a simpler test case with just a processor, a tank, a multitank and a program transfering from one to the other?

**Comment by Unadvoidable** [comment]
# Bug
**Description**
- Moving liquid crystal out of the internal tank doesn't work
<s>- Works with other std fluids (Water, Lava)</s>
- Using workarroud from https://github.com/McJty/RFToolsControl/issues/33

**Code**
- [lct.txt](https://github.com/McJty/RFToolsControl/files/634736/lct.txt)

**Setup**
![image](https://cloud.githubusercontent.com/assets/4508203/20939109/d080c110-bbed-11e6-99bc-7eeaeab07403.png)
![image](https://cloud.githubusercontent.com/assets/4508203/20939070/b100486a-bbed-11e6-94fa-5f1cf662e081.png)
![image](https://cloud.githubusercontent.com/assets/4508203/20939078/b9e55f9c-bbed-11e6-9956-c2aa2bb9c1b3.png)

# Workarround
**Desctiption**
- Specify a access direction in code (North in this example)
- configure it on the tank to the corresponding (input / output)

**Code**
- [lct2.txt](https://github.com/McJty/RFToolsControl/files/634824/lct2.txt)

**Setup**
![image](https://cloud.githubusercontent.com/assets/4508203/20940705/054c4814-bbf4-11e6-8888-528c69c6e9dd.png)


# Suggestion
Maybe this could be solved by loosen up the strict access rules of the tanks. 
But in THIS case, its not the Multitank causing the "problem", but the std DR-tanks
In any case, you should catch this event if it didnt actually move the liquid out (eg. no liquid support)

**Comment by McJty** [comment]
Should be fixed next release (1.6.2, in a moment)
