### ISSUE TITLE
UnsupportedOperationException opening Crafting Station

### ISSUE THREAD

**Issue by Ommina** [McJty/RFToolsControl#34]
Today I upgraded to rftoolsctrl-1.1x-1.6.0.jar (along with the newly release 1.1x versions of the other rftools mods).  With the change (I presume!), the RFToolsControl crafting setup I was working with before now fails with an exception in the client log.

http://pastebin.com/VKaV4fwq

The client does _not_ crash, so this is not a full crash-report.   But nothing is displayed in the GUI for the Crafting Station either.

rftoolsctrl-1.1x-1.6.0
mcjtylib-1.1x-2.3.0
compatlayer-1.10-0.1.0

forge 2139.
jre1.8.0_101

Edit: For giggles, I destroyed the crafting cards, and replaced them with a single "stone -> stone button" card.  No change.

**Comment by McJty** [comment]
I'll fix this in the upcoming release later today
