### ISSUE TITLE
crafting recipes not shown in crafting station?

### ISSUE THREAD

**Issue by JuliCash** [McJty/RFToolsControl#35]
I dont know, if im making anything wrong, but since the last update, i dont see any recipes in the crafting station anymore. The processor find the crafting station, but there are no recipes shown, it worked before. Tried it with the crafting cards in a workbench or in a regular chest

thx

**Comment by McJty** [comment]
Last update is? Also what version of MC?

**Comment by JuliCash** [comment]
1.10.2 with curse launcher.. and i have all the latest rftools mods (that required that compact layered thing)

**Comment by McJty** [comment]
What version of rftools control? Please be specific

**Comment by JuliCash** [comment]
1.1x. 1.60

**Comment by McJty** [comment]
That's not latest. Try 1.6.1 which was released today

**Comment by JuliCash** [comment]
that helped thx

love your mods <3
