### ISSUE TITLE
Network Card and Advanced Network Card incorrect range

### ISSUE THREAD

**Issue by martinhoite** [McJty/RFToolsControl#36]
Advanced Network Card's tooltip says it covers a 33x33x33 area, yet it only covers a 17x17x17 area.

Network Card's tooltip says it covers a 17x17x17 area, yet it only covers 9x9x9

Minor bug, but is it a tooltip bug, or a code bug?

![2016-12-06_17 53 41](https://cloud.githubusercontent.com/assets/5943291/20934965/44e8af56-bbdd-11e6-8a9d-f879204ea541.png)
**World0 is above the processor, World17 is exactly 17 blocks away, World33 is exactly 33 blocks away**

As seen here:
![2016-12-06_17 55 26](https://cloud.githubusercontent.com/assets/5943291/20934969/4777a3da-bbdd-11e6-8bbc-eac974c8c807.png)

Above screenshots are from a singleplayer world, also tested on server (versions stated below).

Tried inserting multiple network cards to see if that made a difference - it didn't (I'm assuming that's intentional anyway though).

Inserting an advanced and a normal network card, makes the processor only account for the normal one as well, is that intended though?

Let me know if you need me to test anything for you.

Versions:
Running a server with Direwolf20 1.10 pack (version 1.0.0)
RFtools control version: 1.5.2

**Comment by McJty** [comment]
It is a 33x33x33 area with the processor in the middle. So that means 17 in each direction (starting from the processor)

**Comment by martinhoite** [comment]
My oh my I feel stupid now.
Closing...
