### ISSUE TITLE
Can't push items into SAG Mill

### ISSUE THREAD

**Issue by davqvist** [McJty/RFToolsControl#37]
I want to fetch Iron Ore from my storage scanner and push it into the SAG Mill. When I do that the items stay in the Processor. When I exchange the SAG Mill with a Furnace or a Chest, it works fine, but with the SAG Mill it doesn't.

Here's what I have configured:
Inv: Here I put the Node Name and the Direction. I don't think I made a mistake here because I tried using a chest on the same spot and it worked also I put the SAG for testing directly beside the Processor and it didn't work either.
Slot: Here I use 0. I checked the slot number with the ESD from Actually Additions and the Input Slot for the SAG Mill is apparently 0, but I tried other numbers and no number as well and nothing of those worked.
Amount: I tried empty and 1, both didn't work.
SlotIn: 0. Again this can't be the problem as pushing the items into a chest and a furnace worked.

Not sure if this problem is yours or EnderIO's fault. As interacting with the SAG Mill with pipes, hoppers and the ESD works, I figured it might be a RFTools Control problem. I also tried debugging with db debug and db s, but that didn't really help me as I don't really a get an error message.

Edit:
RFTools Control 1.1x-1.6.2
EnderIO 1.10.2-3.0.1.138_beta
Forge 12.18.2.2166
Minecraft 1.10.2

**Comment by McJty** [comment]
I also had issues with enderio machines. I could get it to work by accessing the machines with a side and then properly configuring that side on the sag mill. Let me know if that helps for you

**Comment by davqvist** [comment]
Thanks a lot. That worked for me. Haven't considered that at all.
