### ISSUE TITLE
Processor can't fetch lava from Deep resonance tank

### ISSUE THREAD

**Issue by Darkere** [McJty/RFToolsControl#39]
I set up a program to fetch liquid from a tank and I'm just getting a 0 as log message without anything happening. Here's me hoping I'm not doing something stupid wrong.

Inserting a bucket to only fetch specific Liquids doesn't work at all.
Version  1.11-1.6.3

**Comment by McJty** [comment]
Can you give more information? Did you specify a side or not? A bit more details would be nice

**Comment by Darkere** [comment]
Yes, I tried specifying a side which did nothing. The program is literally every 20 ticks move 100ml of lava from the tank nothing more. I also allocated some storage of the Multitank inside the processor.

**Comment by McJty** [comment]
Can you copy/paste the program here? (just do ctrl-a/ctrl-c in the programmer and paste it here)

**Comment by Darkere** [comment]
My program is just this.
`[
  {
    "pos": {
      "x": 2,
      "y": 2
    },
    "opcode": {
      "id": "do_fetchliquid",
      "primary": "R",
      "parameters": [
        {
          "type": "inventory",
          "value": {
            "side": "south",
            "intside": "up"
          }
        },
        {
          "type": "integer",
          "value": {
            "v": 100
          }
        },
        {
          "type": "fluid",
          "value": {
            "null": true
          }
        },
        {
          "type": "integer",
          "value": {
            "v": 0
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 1,
      "y": 2
    },
    "opcode": {
      "id": "ev_timer",
      "primary": "R",
      "parameters": [
        {
          "type": "integer",
          "value": {
            "v": 50
          }
        },
        {
          "type": "boolean",
          "value": {
            "null": true
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 3,
      "y": 2
    },
    "opcode": {
      "id": "do_log",
      "primary": "R",
      "parameters": [
        {
          "type": "string",
          "value": {
            "fun": "last_str"
          }
        }
      ]
    }
  }
]`

**Comment by McJty** [comment]
Did you try the fetchliquid without a side too? i.e. just say 'south' and don't specify the intside

**Comment by Darkere** [comment]
Great now I just need to figure out why this didn't work the last time I tried it... Probably a combination of fixing something else and forgetting to set everything back to zero after I found out what it was...
