### ISSUE TITLE
Servercrash by ProgException: Too many events

### ISSUE THREAD

**Issue by ronplanken** [McJty/RFToolsControl#42]
Server crashes when a player connects. Looks similar to https://github.com/McJty/RFToolsControl/issues/14 but this is an newer version and should be fixed?

http://pastebin.com/raw/3ZyLXcLd

rftools{5.62} [RFTools] (rftools-1.10-5.62.jar) 
rftoolscontrol{1.5.2} [RFTools Control] (rftoolsctrl-1.10-1.5.2.jar)

**Comment by ronplanken** [comment]
Maybe it helps: The RFTools Controller was out of power and was being powered by a wireless RF item from ExtraUtilities2.

**Comment by McJty** [comment]
Yes, you hit a built-in protection which was caused by being out of power and getting events. But the exception should have been catched though so there is certainly a bug

**Comment by ronplanken** [comment]
Closed after a couple of years <3
