### ISSUE TITLE
[MC 1.10.2] [rftoolsctrl-1.1x-1.6.3] Advanced Network Card is 17x17x17

### ISSUE THREAD

**Issue by nikkimas** [McJty/RFToolsControl#48]
Hey,
as written in the title, I only get a 17x17x17 range with the Advanced Network Card.
I don't know what else there is to say about that ^^

**Comment by McJty** [comment]
It is 34x34x34 with the processor in the middle. So it goes 17 in all directions

**Comment by nikkimas** [comment]
ohhh, sry. didnt even think about it ^^". 
Thank you and have a great new Year :)
