### ISSUE TITLE
Possible bug with crafting cards

### ISSUE THREAD

**Issue by Superfraggle** [McJty/RFToolsControl#50]
In the Gui for the crafting card it states "the output does not have to actually correspond with the actual output" 

However if I try to make, say a smelting card for stone, with cobble as the ingredients, it saves the ingredients, but the output is not saved. 

Version 1.6.3

**Comment by McJty** [comment]
What version of Minecraft?

**Comment by Superfraggle** [comment]
Sorry its 1.10.2 tested on both the direwolf20 pack and the skyfactory3 pack on curse.

**Comment by McJty** [comment]
You are not pressing the 'Update' button I hope?

**Comment by Superfraggle** [comment]
yes, now I feel stupid, I made the incorrect assumption that the update button was a Save button. Thank you, sorry to have wasted your time
