### ISSUE TITLE
[Suggestion] Filtering with NBT.

### ISSUE THREAD

**Issue by ThePocketSoul** [McJty/RFToolsControl#6]
It would be great to have filtering of NBT data when fetching and pushing items (Since some items in other mods and base RFTools use NBT for various things).

**Comment by McJty** [comment]
Good idea. I'll add something like that

**Comment by McJty** [comment]
Turns out that reading arbitrary NBT values would be too OP/cheaty. There are many items that have hidden information in NBT that you're not supposed to know about. However, I am busy implementing an opcode that lets you at least compare a specific NBT tag between two items.
