### ISSUE TITLE
Processor gfx-select event reports offset click coordinates

### ISSUE THREAD

**Issue by shabble** [McJty/RFToolsControl#60]
Using a Processor + Vector module with a program that listens on the `gfx-select` event, the coordinates returned do not accurately reflect where the user clicks the screen.

Using the horribly written program [here](https://gist.github.com/shabble/7f38ba5e8597a592052b0f6d801409b8), it can hopefully be seen that the reported click coordinates do not correspond with the drawn coordinate system.

In the images, the small green square is the reported click coords. In teh first image, the crosshair is exactly where the click occurred.

![rftctrl-clickalign-centre](https://cloud.githubusercontent.com/assets/97020/22402521/2d033e76-e5f2-11e6-83d2-d92d3c2f58ce.png)

This image makes it a bit easier to see the 2nd pinkish square, which is manually offset to try to compensate for the problem. The values here are (x+2, y+10), which are pretty good, but not perfect. It (may) also appear to vary a bit across the screen, and on the angle at which the player is interacting with the screen.

![rftctrl-clickalign-nohud](https://cloud.githubusercontent.com/assets/97020/22402522/2f79c4cc-e5f2-11e6-93ce-5051866a7dd9.png)

**Comment by McJty** [comment]
I fixed the problem for next release. Note that due to limitations in how rftools screens work you cannot currently access the top 7 coordinates of the screen. That was also the reason for this problem
