### ISSUE TITLE
Console module for screens doesn't understand colour format codes?

### ISSUE THREAD

**Issue by shabble** [McJty/RFToolsControl#62]
![rftctrl-console-colourcode](https://cloud.githubusercontent.com/assets/97020/22406951/a207c2ca-e654-11e6-810d-9c1e2f1d58ba.png)

Generic output from a processor into a screen with a console module. I believe the `§c` stuff is text colour formatting codes that the screen renderer should either interpret, or strip.

It displays normally (that is, with those bits in red) in the internal GUI console and the floating processor console log.

**Comment by McJty** [comment]
This has to do with the new unicode support. If you switch back the screen to use the old vanilla font it will work. I'll add support for this soon

**Comment by McJty** [comment]
Fixed in upcoming new release of McJtyLib (this mod needs no update for this)
