### ISSUE TITLE
storage scanner allows inappropriate items into processor slots

### ISSUE THREAD

**Issue by shabble** [McJty/RFToolsControl#63]
When items are inserted via a RFTools storage scanner, they appear to bypass the slot-appropriateness checks, and will fill from the low-numbered slots first.

Attached images show example:

![rftctrl-badinsert](https://cloud.githubusercontent.com/assets/97020/22450482/e3e1edc8-e75e-11e6-9a86-cd3f95ebbd19.png)
![rftctrl-naughtyscanner](https://cloud.githubusercontent.com/assets/97020/22450483/e3eb01e2-e75e-11e6-82b6-9c15619b3ca2.png)

Trying to pipe in items via any of the other usual means (hopper, EIO conduit, transfer nodes, etc) doesn't appear to allow anything in.

I'm not sure if this is the fault of the processor, or the storage scanner.

If possible, it would be nice for the scanner (and potentially other item transfer methods) to be able to appropriately access (some or all) of the slots, preferably at least the program card ones.

* MC: 1.10.2
* rftools-1.1x-5.82.jar
* rftoolsctrl-1.1x-1.6.4.jar

**Comment by McJty** [comment]
Should no longer happen next version
