### ISSUE TITLE
[Question] Is it possible to compare two string ?

### ISSUE THREAD

**Issue by adriengou** [McJty/RFToolsControl#64]
I want to know if the name of an item contain the word "ore" . Is there a way to do this ? ore just a way to know if two items have the same name ?

**Comment by McJty** [comment]
The opcode 'test_eq_var' can test if a variable is equal to the last value. This works for strings. There is nothing for 'contains' yet. I might add that soon

**Comment by adriengou** [comment]
Sorry for using this topic for an other question but, can a processor push an item in a slot if the item is not meant to go on this slot( push iron ingot in fuel slot of a furnace for example) ?

**Comment by McJty** [comment]
If the furnace properly prevents this then it should not be possible

**Comment by adriengou** [comment]
ok, thanks
