### ISSUE TITLE
Recurring crash from processor: "ProgException: Too many events"

### ISSUE THREAD

**Issue by shabble** [McJty/RFToolsControl#65]
after creating and running a (probably buggy) autocrafting program, I've managed to crash the game, and subsequently crashes when trying to reload the world with a similar cause.

I don't have the exact program handy since I can't get into the save, but I was manually (via `signal xxx` in the processor console) kicking off a handler which makes an autocraft request.

Just before it crashed teh first time, I saw on the processor debug output that the number of entries in the "waiting" state was growing very rapidly - probably somewhere around 7000+ when it crashed.

Might be somehow related to crafting or other signals with single=true set, but somehow backing up anyway?

Attached are 2 crashlogs. First is the original game crash, 2nd is similar, when I try to reload the world.
[crash-2017-02-05_21.21.07-server.txt](https://github.com/McJty/RFToolsControl/files/755511/crash-2017-02-05_21.21.07-server.txt)
[crash-2017-02-05_21.15.49-server.txt](https://github.com/McJty/RFToolsControl/files/755512/crash-2017-02-05_21.15.49-server.txt)

If I can figure out how to disable or nuke the processor I'll add some further details with the program that was running.

Poking around with NBTExplorer, the Processor TE responsible has:
`waiting: 7100 entries`, each of which appears identical, containing `ticket: #rsio#up#-##56`, which I'm guessing is some crafting ticket?

`events` tag has 100 entries, many (all?) of which look to be something like: `{ single: 1, card: 0, index: 37, ticket: "#rsio#up#-##56" }`

**Comment by shabble** [comment]
nuking the processor let me get back in, I think the program in question was: https://gist.github.com/shabble/ec8cb1e866dd1990954746c90adcb2bd

(Note the accidental loop at (8,3) that was probably causing the silly amounts of pending events that took down the game, but ideally there would be some way of recovering from this sort of situation without savegame hacking)

**Comment by McJty** [comment]
I added protection against this for next version
