### ISSUE TITLE
Event: Message may not receive variable when sent to self

### ISSUE THREAD

**Issue by shabble** [McJty/RFToolsControl#67]
When using the do_message/event_message opcodes in a single program card, the event is reliably triggered, but the variable provided is not consistently received.

Test program is https://gist.github.com/shabble/206d1a12da537647603f3cf414307942

Place in a processor in slot 1, with item-slot 2 containing a network identifier bound to the same processor.

Execute with `signal vec2`.

If there is only a single CPU, or if exclusive mode is enabled, the message event handler will not receive the variable.

If >1 CPU is available (and not exclusive) the variable will be received and printed as expected.
If 2 CPUs are present and a second program listens for the event, both will receive it, but only one will be passed the variable. More CPUs (possibly N+1) means both will receive the var.

I'm not 100% sure what I'd expect to happen here, probably either: 

a) it's queued like any other event when there aren't any cores available, and runs after the caller sequence completes

b) it's dropped if there are no cores, so the handler doesn't fire at all.

In either case, getting the event but not the associated variable seems odd/wrong.

Version:

* minecraft 1.10.2
* rftoolsctrl-1.1x-1.6.4.jar

**Comment by McJty** [comment]
I found the reason for the bug. The problem was that events that cannot be handled immediatelly gets pushed on a queue. And they are executed when there is an available core. The problem is that the parameter is ignored in that case. I will fix this for next release
