### ISSUE TITLE
Item Metadata, Crafting Station, Crafting Cards and Event:craft weirdness

### ISSUE THREAD

**Issue by Hjaldar** [McJty/RFToolsControl#7]
I am attempting to set up crafting of Blood Magic slates using RFTools Control. The 5 different slates have the same item ID but different metadata. I tested with just the two lowest tier slates, the Blank Slate (bloodmagic:ItemSlate:0) and the Reinforced Slate (bloodmagic:ItemSlate:1).

Everything works perfectly when I have only a single crafting card, either for the Blank Slate or for the Reinforced Slate, in the workbench. The correct result is produced when I click the appropriate recipe in the crafting station.

When I have more than one crafting card in the workbench (or any inventory - also tested with a vanilla chest), clicking on either the Blank Slate or Reinforced Slate in the crafting station produces the same item, but which item it is depends upon the arrangement of crafting cards in the workbench. If the crafting card for the Blank Slate is in the lower numbered slot in the workbench, then Blank Slates are produced irrespective of which recipe I click in the crafting station. If the crafting card for the Reinforced Slate is in the lower numbered slot in the workbench, then Reinforced Slates are produced irrespective of which recipe I click in the crafting station. The item icon displayed in the progress section of the crafting station matches the item that will be produced.

My program is [here](http://pastebin.com/7D3WJ364). Relative to the processor, the workbench is west, the crafting station is east and the blood altar is south.

Please let me know if I can assist with further information or testing.

**Comment by McJty** [comment]
I know what the problem is. Will see if I can fix this easily

**Comment by McJty** [comment]
Fixed next release (later today)

**Comment by Hjaldar** [comment]
Thanks :) (and for the mod)
