### ISSUE TITLE
[Question] Crafting Station and "Bad parameters" ?

### ISSUE THREAD

**Issue by adriengou** [McJty/RFToolsControl#70]
Hello, i have an autocrafting setup with a metallurgic infuser and i have an error that i don't understand:
http://imgur.com/a/HNKav
Can someone help me ? Thanks in advance.

**Comment by McJty** [comment]
Can you copy/paste the program to a bpaste or pastebin so that I can copy it? Or include it here?

**Comment by adriengou** [comment]
If you scroll down to the last image, there is the programe below it.
http://pastebin.com/XLgbSkh1

**Comment by McJty** [comment]
ah right

**Comment by adriengou** [comment]
I found the problem, it won't let me use the craft event with a set item, is there a way to fix this ?
EDIT: nevermind i'm dumb, i forgot to put the crafting craft with the craft i wanted to autmate.
So, problem solved !

**Comment by McJty** [comment]
Craft event with a set item?
