### ISSUE TITLE
Unable to fetch from storage

### ISSUE THREAD

**Issue by Xnosis** [McJty/RFToolsControl#78]
Great mod!

Having some trouble with directly fetching an item from RFTools storage scanner to an internal slot in the processor. Throws out 'internal error'.

Able to eval the item (name/count) and print to debug. If I use get ingredients it will fetch the items from storage and put them in the processor just fine.

I can fetch items from a specified container (modular storage, crafter, etc) and it gets placed in the processor as expected.

Error only appears when trying to fetch directly from storage scanner to the processor.

Debug info doesn't help much to explain what is going wrong. Pastebin has the basic test setup.

Push button on top of processor > fetch 5 redstone from storage > place in slot 0 of processor

[https://pastebin.com/mqHsXhuz](url)

Running 1.11.2
rftoolsctrl-1.1x-1.6.6.jar
rftools-1.1x-5.91.jar

**Comment by McJty** [comment]
I'll check it out as soon as I find a little time

**Comment by McJty** [comment]
Unfortunatelly I waited too long and the pastebin has expired. Could you just explain in words what you were doing exactly?
