### ISSUE TITLE
Syringe identification

### ISSUE THREAD

**Issue by meson11** [McJty/RFToolsControl#79]
i want to change the syringes in a spawner per button. if you click on button zombie e.g. the syringe in the spawner get extracted and replaced with the zombie syringe. the problem: rftools control, in special fetch item and push item cannot recognize different syringes.

**Comment by tofof** [comment]
This is related to NBT blindness, see #93.

**Comment by McJty** [comment]
I updated #93 as I have no idea how to solve this problem in a nice way

**Comment by McJty** [comment]
Ok, in next version (1.7.0) crafting cards will have an extra feature to allow 'strict nbt' matching for getting ingredients. This should fix this issue. get_ingredients and get_ingredients_smart will honor that flag
