### ISSUE TITLE
Show Slotnumbers in Processor GUI

### ISSUE THREAD

**Issue by MaPePeR** [McJty/RFToolsControl#8]

**Comment by McJty** [comment]
Remember that slot numbers are relative. I can't really show them in the processor because they wouldn't always be the same as the slot numbers in the programs. Those depend on how you allocated the slots. I can show them while you're allocating them though so that's something that I will do

**Comment by MaPePeR** [comment]
Yea, that is what i intended.

That would have saved Dire a lot of time in the episode that went live today 😉

**Comment by McJty** [comment]
I just implemented this. You can see it on my twitter:

https://twitter.com/McJty/status/782231688797618181
