### ISSUE TITLE
Too Many Events

### ISSUE THREAD

**Issue by MinoCraft** [McJty/RFToolsControl#86]
Hello ! 

I play with Minecraft 1.10.2, Forge 12.18.3.2281 and the last version of RF Tools Control (1.1x - 1.6.8)

I'm trying to make a level emitter prog for control machines start and stop in my base. I don't know if my problem is a bug but:
When I'm using an operation "send message", I have this log on the processor console as you can see on the screenshot
![2017-06-08_22 12 07](https://user-images.githubusercontent.com/4315922/26949217-56fe5c70-4c99-11e7-84c5-a1d9e33f2c5f.png)
You can find the prog here: https://pastebin.com/8rJLBtZ6
![2017-06-08_22 11 47](https://user-images.githubusercontent.com/4315922/26949256-8ae7df3e-4c99-11e7-867f-b98bba40cc6d.png)
 Thanks in Advance ;)

**Comment by McJty** [comment]
That usually indicates a bug in your program as it is probably firing a new event while the program is still running and thus gets into an infinite loop. I have no time right now to check it out but maybe this already helps you

**Comment by MinoCraft** [comment]
Yeap you helped me =) I've increased the time in the repeat operation and it work fine ^^
Thanks for you help !
