### ISSUE TITLE
is this "test" bug?

### ISSUE THREAD

**Issue by blinkinglight** [McJty/RFToolsControl#87]
hi, 
i have this program: https://pastebin.com/8U96BRvg var0 i set in [1,0] manualy - "akward potion"
and then checking brewing stand slot 0 ( bottom left ) and set it to var1. i checked in processor, both potions are different. so:

NBT test: akward potion = water potion = false (ok)
NBT test: akward potion = mundane potion = true? expected false
NBT test: akward potion = akdward potion = true expected true
just simple test var0 with var1 = always returns true.

(ftb beyond 1.8.1 modpack, rfcontrols 1.6.8 )

**Comment by McJty** [comment]
The equality test of itemstacks just tests on the item itself and not anything else. you need to manually compare meta/nbt yourselves if you want that
