### ISSUE TITLE
Don't ask for the Program name every time when saving

### ISSUE THREAD

**Issue by MaPePeR** [McJty/RFToolsControl#9]

**Comment by McJty** [comment]
Problem is, when should I ask it and how to change it?

**Comment by MaPePeR** [comment]
My Ideas:

* Anvil renaming
* Only ask the first time and then..
    * keep the name forever until the program card is "reset" in the crafting grid or something like that
    * have an additional rename button
    * shift-clicking the save button will show the rename button again
* Have a Textbox in the GUI that always shows the name and always allows you to edit it. This has the benefit that you will easily see the name of the program that is currently loaded, too.

**Comment by Aedda** [comment]
I was going to request this as well. I personally like the idea of a text field with the name. Initiate it with the program name on Load so that the name is consistent with the opcode grid.

**Comment by McJty** [comment]
Problem is that I literally have no place to put such a name even though it will be the ideal solution. Have to think about this more

**Comment by Erelaszun** [comment]
if you can read the use of modifier keys (SHIFT, CTRL, etc), maybe a SHIFT + Click Save will request the user to enter a new name... if that is possible... and that can be easily added to the tooltip.... and, for new programs, a simple "if name = null" eval to request a name for the first save.

**Comment by McJty** [comment]
Implemented last solution for next version
