### ISSUE TITLE
Crafting station ignores item name and meta when NBT is equal

### ISSUE THREAD

**Issue by knexer** [McJty/RFToolsControl#94]
It appears that a crafting station can request the crafting of the wrong item if two craftable items have the same NBT tags but different item names or metadata.  For example, a sponge axe head and a sponge tool rod from Tinkers' Construct have the same NBT data but are completely different items, but the crafting station will simply craft whichever of those it finds first.

Forgive me, I didn't attempt to reproduce this bug, I just spotted it in the code when doing research for https://github.com/McJty/RFToolsControl/issues/93.  I could be wrong.

Offending lines:
https://github.com/McJty/RFToolsControl/blob/1.11/src/main/java/mcjty/rftoolscontrol/blocks/craftingstation/CraftingStationTileEntity.java#L381

**Comment by tofof** [comment]
Agreed from a glance at the code that this should be a problem. Doesn't look like it's McJty's fault; I think this bad logic got intruduced in PR #30.

**Comment by McJty** [comment]
Can you pinpoint where exactly? I can see if I can fix it then

**Comment by tofof** [comment]
I mean.. he did already.

https://github.com/McJty/RFToolsControl/blob/27e90c36c4cce6f3e9de916b60ee0b3d02e53792/src/main/java/mcjty/rftoolscontrol/blocks/craftingstation/CraftingStationTileEntity.java#L383

That logic returns immediately on an nbt-tag match, without checking that
item name and meta also match.

Fix is just as easy, L381-L389 should be replaced with something like...

for (ItemStack item : items) {
    if (item.getItemDamage() == meta &&
itemName.equals(item.getItem().getRegistryName().toString())) {
        if (item.hasTagCompound()) {
            if (nbtString.equalsIgnoreCase(item.serializeNBT().toString()))
{
                return index;
            }
        } else return index;
    }
    index++;
}

**Comment by tofof** [comment]
I mean.. he did already. Maybe you're looking at the master branch, which doesn't contain it? Both 1.11 and 1.12 have the error though.

https://github.com/McJty/RFToolsControl/blob/27e90c36c4cce6f3e9de916b60ee0b3d02e53792/src/main/java/mcjty/rftoolscontrol/blocks/craftingstation/CraftingStationTileEntity.java#L382-L388

That logic returns immediately on an nbt-tag match, without checking that
item name and meta also match.

Fix is easy, L381-L389 in 1.11 (L385-L394 in 1.12) should be replaced with something like...

```
for (ItemStack item : items) {
    if (item.getItemDamage() == meta && itemName.equals(item.getItem().getRegistryName().toString())) {
        if (item.hasTagCompound()) {
            if (nbtString.equalsIgnoreCase(item.serializeNBT().toString())) {
                return index;
            }
        } else return index;
    }
    index++;
}
```

**Comment by McJty** [comment]
Ok. Thanks. I'll fix it like that for next release

**Comment by tofof** [comment]
I see you closed this issue, but it seems appropriate to add here rather than opening a new issue:

These lines have the same logical error, returning something on basis of matching NBT alone without checking item equality, etc.

https://github.com/McJty/RFToolsControl/blob/072fdc8c8253bde005179347e06a572980e96069/src/main/java/mcjty/rftoolscontrol/blocks/processor/ProcessorTileEntity.java#L855-L861

**Comment by McJty** [comment]
ok I will check this
