### ISSUE TITLE
[Feature Request] Export/Import Programs

### ISSUE THREAD

**Issue by InjuredWolf** [McJty/RFToolsControl#95]
If this is already a thing, let me know (and close this).

It would be great to be able to export programs to be able to share them with other players/use them in other worlds. Would, of course, have to have an import system as well. So far I haven't seen a way to do this as of yet.

**Comment by McJty** [comment]
Ctrl-A (select all), Ctrl-C to copy. You can also Ctrl-V.
The copied program can be pasted in notepad or whatever as a json and moved to another computer that way

**Comment by InjuredWolf** [comment]
Oh. Was not aware. Thankyou :)
