### ISSUE TITLE
1.12 Powercell Linking Crash

### ISSUE THREAD

**Issue by Razorfin8** [McJty/RFToolsControl#96]
Pastebin: https://pastebin.com/YaHH9VVA
Mod version: What ever ATM3 is using

I'm playing the ATM3 pack.  In a creative world, I used TechReborn's Windmills (4) and connected them with glass fiber cables to a advanced powercell.  Then I made a Techreborn watermill setup (10) and connected to a powercell.  I made the link cards on the windmill cell, then as soon as i inserted into the watermill cell, I crashed and MC threw a null pointer that is pointing at RFTools Powercell (SEE ABOVE).  It seems as if the link card did get loaded before the world crashed as I can not get back into the world without instantly crashing. Huge problem as this setup was what I was going to use.  Does it have something to do with converting EU to RF?

Edit: pretty sure this is RFTools but I also posted to techreborn as well to be safe since the log does call it out too.

**Comment by McJty** [comment]
It seems that TechReborn is trying to send energy to the powercells clientside which is not legal. In that case it is their fault

**Comment by modmuss50** [comment]
Yep, your right. You might want to gracefully handle it, but it should work now.
