### ISSUE TITLE
Inventory opcode not working?

### ISSUE THREAD

**Issue by mike-potter** [McJty/RFToolsControl#97]
I have a storage scanner linked to a storage card in the processor.  If I use the Inventory opcode with a blank argument and output to console, it just scrolls a lot of blank lines.  If I try to reference this as the last_inv and fetch the first item to see what it is, I get "[4,2] Missing parameter".  

What I'd ultimately like to do is loop through machines found by the storage scanner to query it, but just learning how this works to start.  Seems like the Inventory opcode returns *something* but nothing that requires an Inventory object using last_inv seems to work.

(Note, I also tried storing the result of the Inventory opcode to a variable and then referenced the variable in the GetItem opcode, but still didn't work)

rftoolsctrl-1.1x-1.6.8.jar in the FTB Beyond pack.

Any ideas?

Here is the simple program:

```
[
  {
    "pos": {
      "x": 2,
      "y": 2
    },
    "opcode": {
      "id": "ev_rs_on",
      "primary": "R",
      "parameters": [
        {
          "type": "side",
          "value": {
            "side": "west"
          }
        },
        {
          "type": "boolean",
          "value": {
            "null": true
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 5,
      "y": 2
    },
    "opcode": {
      "id": "do_log",
      "primary": "L",
      "parameters": [
        {
          "type": "string",
          "value": {
            "fun": "last_str"
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 4,
      "y": 2
    },
    "opcode": {
      "id": "eval_getitem",
      "primary": "R",
      "parameters": [
        {
          "type": "inventory",
          "value": {
            "fun": "last_inv"
          }
        },
        {
          "type": "integer",
          "value": {
            "v": 0
          }
        }
      ]
    }
  },
  {
    "pos": {
      "x": 3,
      "y": 2
    },
    "opcode": {
      "id": "eval_inventory",
      "primary": "R",
      "parameters": [
        {
          "type": "inventory",
          "value": {
            "null": true
          }
        }
      ]
    }
  }
]
```

**Comment by McJty** [comment]
If a parameter is missing you should check in the programmer on that opcode and see what parameter you forgot to use
